### ISSUE TITLE
Stale branches

### ISSUE THREAD

**Issue by nelson-barnett** [The-Lammert-Lab/tinnitus-reconstruction#219]
There are a few stale branches that look like they can be easily deleted. I just didn't want to in case you knew something about them that I didn't.

**Comment by alec-hoyland** [comment]
Feel free to delete

On May 22, 2023 9:25:33 PM EDT, Nelson Barnett ***@***.***> wrote:
>There are a few stale branches that look like they can be easily deleted. I just didn't want to in case you knew something about them that I didn't.
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/The-Lammert-Lab/tinnitus-reconstruction/issues/219
>You are receiving this because you were assigned.
>
>Message ID: ***@***.***>
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
